### PR TITLE
 iOS 13 support

### LINKED ISSUE #327: Unable to connect with iPad Pro 10.5" on iPadOS 13.1
Hello everyone,

I'm having some difficulties trying to connect my iPad Pro 10.5" running iPadOS 13.1.  There error message is the following:

Unable to connect to Jared’s iPad (1518f84dd3281f1b070fadd7398eba5501be4b4b)
  Please verify that Settings > Safari > Advanced > Web Inspector = ON

The output of ios_webkit_debug_proxy -V is:
ios_webkit_debug_proxy 1.8.5
Built with libimobiledevice v1.2.1, libplist v2.0.0

Any help would be appreciated.  Thanks!

### PR DESCRIPTION
**Pull request by artygus**
Brings in ssl support 

Solution is less than perfect since it
- uses private libimobiledevice structures
- ignores gnutls ssl support
- doesn't clean up ssl sessions

resolves #327 #314 #328 
closes #317

### CODE REVIEW

**Comment by artygus** [comment]
⚠️ Contains untested code after clean up

**Comment by githubdhina** [comment]
> Brings in ssl support
> 
> Solution is less than perfect since it
> 
> * uses private libimobiledevice structures
> * ignores gnutls ssl support
> * doesn't clean up ssl sessions
> 
> resolves #327 #314 #328
> closes #317

I tried building from master, but I see the following when trying to see the listening devices:
Screenshot 2019-10-08 at 1 13 48 PM

**Comment by artygus** [comment]
@githubdhina did you build libimobiledevice with gnutls support?

**Comment by githubdhina** [comment]
@artygus, thanks for the response. No, I did not build the libimobiledevice with gnutls support. Can you help me with the steps please?

**Comment by artygus** [comment]
@githubdhina you don't have to build it with gnutls, it's not supported by iwdp atm. what's you environment? how do you build libimobiledevice? from master?

**Comment by githubdhina** [comment]
@artygus, my environment is macOS Mojave Version 10.14.6. 
libimobiledevice version 1.2.0_4 was installed via homebrew.

**Comment by artygus** [comment]
libimobiledevice should be installed with --HEAD flag

**Comment by githubdhina** [comment]
@artygus , installing libimobiledevice with --HEAD flag fixed it. Thanks.

**Comment by zacaj** [comment]
Is there going to be a new release with this soon?  Tried to build it myself but don't think I have the setup....   I see that the version is still on 1.8.5 though?

**Pull request merged**
